### ISSUE TITLE
Error module bignum.node

### ISSUE THREAD

**Issue by volkovpv** [justmoon/node-bignum#100]
Hello. I get error:

Error: The module '/var/www/my-projec/node_modules/bignum/binding/bignum.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

OS: LInux Mint 18 x64
Node: v8.7.0
bignum: 0.12.5

But I don't have error with Node 6x.

**Comment by milaas** [comment]
hello I am able to setup bignum..

> bignum@0.12.5 install /home/michel/z-nomp/node-bignum
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://rvagg-node.s3-us-west-2.amazonaws.com/bignum/v0.12.5/bignum-v0.12.5-node-v64-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bignum@0.12.5 and node@10.0.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 

any ideas???

**Comment by rvagg** [comment]
Please try again with the latest version. You'll need a compiler in place though.
