### ISSUE TITLE
Failed at the bignum@0.11.0 install script

### ISSUE THREAD

**Issue by shailendra4chat** [justmoon/node-bignum#102]
I am using "node": "7.10.0", "npm": "4.2.0" and getting error 
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bignum@0.11.0 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bignum@0.11.0 install script 'node-gyp configure build'.

It was working fine with "node": "5.5.0", "npm": "3.8.3".

Please help and suggest what needs to be done to fix this issue.

**Comment by aj-ptw** [comment]
same issue with node 6.9.5

**Comment by char1e5** [comment]
Same issue with node 8.9.0

**Comment by adryy5** [comment]
same issue with node 6.11.5

**Comment by anglofox** [comment]
I'm using node 10.0.0 and having the same issue

**Comment by rvagg** [comment]
Please try again with the latest version that's just been published. You will need a compiler in place though.

**Comment by zhangcaiyan** [comment]
这个问题怎么解决的？
