### ISSUE TITLE
Not able to install bignum@0.12.5 in node 8.9.0 linux

### ISSUE THREAD

**Issue by char1e5** [justmoon/node-bignum#103]
```
> bignum@0.12.5 install
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://rvagg-node.s3-us-west-2.amazonaws.com/bignum/v0.12.5/bignum-v0.12.5-node-v57-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bignum@0.12.5 and node@8.9.0 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
gyp ERR! build error 
```

**Comment by rvagg** [comment]
it _should_ just fall back to compiling, do you have compile tools installed on this machine? gcc or clang?

**Comment by vishalmindtickle** [comment]
Same error coming with me.
gcc is installed in server.

**Comment by BitCoinJedi** [comment]
I'm also getting errors :( I even changed the script to pull the git via the url but Im getting the same error.

npm ERR! Linux 4.11.0-1014-azure
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "update"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! bignum@0.12.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the bignum@0.12.5 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bignum package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bignum
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bignum
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/desiluvr/z-nomp/npm-debug.log

**Comment by logicminds** [comment]
There are quite a few deprecations with node 8.9

```
../multihashing.cc:578:18: error: 'NewSymbol' is not a member of 'v8::String'
     exports->Set(String::NewSymbol("quark"), FunctionTemplate::New(quark)->GetFunction());
                  ^
../multihashing.cc:578:73: error: no matching function for call to 'v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))'
     exports->Set(String::NewSymbol("quark"), FunctionTemplate::New(quark)->GetFunction());
                                                                         ^
../multihashing.cc:578:73: note: candidate is:
In file included from /root/.node-gyp/8.9.4/include/node/node.h:63:0,
                 from ../multihashing.cc:1:
/root/.node-gyp/8.9.4/include/node/v8.h:5395:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int, v8::ConstructorBehavior)
   static Local<FunctionTemplate> New(
                                  ^
/root/.node-gyp/8.9.4/include/node/v8.h:5395:34: note:   no known conversion for argument 1 from 'v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}' to 'v8::Isolate*'
../multihashing.cc:579:18: error: 'NewSymbol' is not a member of 'v8::String'
     exports->Set(String::NewSymbol("x11"), FunctionTemplate::New(x11)->GetFunction());
                  ^
../multihashing.cc:579:69: error: no matching function for call to 'v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))'
     exports->Set(String::NewSymbol("x11"), FunctionTemplate::New(x11)->GetFunction());

```

You can run `docker run --ti --rm node:8.9.4 npm install bignum` to see for yourself

**Comment by AndyTyurin** [comment]
I have same problem on node:8.9.4-alpine, any solutions?

**Comment by srijanreddy98** [comment]
I am getting this error

> `if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\Chintu\Documents\Nodejs\allen-torrent-master\allen-torrent-master\node-bignum\binding\bignum.node --module_name=bignum --module_path=C:\Users\Chintu\Documents\Nodejs\allen-torrent-master\allen-torrent-master\node-bignum\binding )  else (node "" configure --fallback-to-build --module=C:\Users\Chintu\Documents\Nodejs\allen-torrent-master\allen-torrent-master\node-bignum\binding\bignum.node --module_name=bignum --module_path=C:\Users\Chintu\Documents\Nodejs\allen-torrent-master\allen-torrent-master\node-bignum\binding )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Python34\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\Chintu\\Documents\\Nodejs\\allen-torrent-master\\allen-torrent-master\\node-bignum\\binding\\bignum.node" "--module_name=bignum" "--module_path=C:\\Users\\Chintu\\Documents\\Nodejs\\allen-torrent-master\\allen-torrent-master\\node-bignum\\binding"
gyp ERR! cwd C:\Users\Chintu\Documents\Nodejs\allen-torrent-master\allen-torrent-master\node-bignum
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\Chintu\Documents\Nodejs\allen-torrent-master\allen-torrent-master\node-bignum\binding\bignum.node --module_name=bignum --module_path=C:\Users\Chintu\Documents\Nodejs\allen-torrent-master\allen-torrent-master\node-bignum\binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Chintu\Documents\Nodejs\allen-torrent-master\allen-torrent-master\node-bignum\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.16299
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Chintu\\Documents\\Nodejs\\allen-torrent-master\\allen-torrent-master\\node-bignum\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Chintu\Documents\Nodejs\allen-torrent-master\allen-torrent-master\node-bignum
node-pre-gyp ERR! node -v v8.9.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\Chintu\Documents\Nodejs\allen-torrent-master\allen-torrent-master\node-bignum\binding\bignum.node --module_name=bignum --module_path=C:\Users\Chintu\Documents\Nodejs\allen-torrent-master\allen-torrent-master\node-bignum\binding' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bignum@0.12.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bignum@0.12.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Chintu\AppData\Roaming\npm-cache\_logs\2018-03-06T13_22_57_481Z-debug.log`

**Comment by thg303** [comment]
any solution for this issue?

**Comment by rvagg** [comment]
New version is published with a new build setup. There are no prebuild binaries available yet so you will still need a compiler in place. For windows have a look at https://github.com/nodejs/node-gyp/blob/master/README.md#on-windows
