### ISSUE TITLE
Converting negative numbers to Buffers

### ISSUE THREAD

**Issue by yefremov** [justmoon/node-bignum#16]
This is more a question: is there any plans when conversion of negative numbers to buffers will be implemented?

As of now I'm doing this to convert negative numbers to Int64:

```javascript
var buf1 = new Buffer(4);
var buf2 = new Buffer(4);

buf1.writeInt32BE(-1, 0);
buf2.writeInt32BE(-1, 0);

// <Buffer ff ff ff ff ff ff ff ff>
var buf3 = Buffer.concat([ buf1, buf2 ]); 
```

It would be very handy to utilize only `bignum` package to achieve the same result.

**Comment by rvagg** [comment]
pull request would be appreciated for new features, this library is kind of in maintenance-mode and new features are likely to only be added by new contributors
