### ISSUE TITLE
.toBuffer(opts) description is not clear for a buffer newbie

### ISSUE THREAD

**Issue by therobwatson** [justmoon/node-bignum#30]
(I wasn't sure where else to ask this:)

I'm trying to take a bignum integer and create a corresponding buffer that is for a 64-bit unsigned big endian.  I'm too uninformed about buffers to know what "size" to set it for the toBuffer call ... is it 64?

**Comment by rvagg** [comment]
closing cause old .. please reopen if you still have a problem
