### ISSUE TITLE
node-gyp configure build failed

### ISSUE THREAD

**Issue by AnnieCyl** [justmoon/node-bignum#38]
Hi all.
I got this when I tried to install bignum, how to fix it? 

C:\Windows\system32>npm install bignum
npm http GET https://registry.npmjs.org/bignum
npm http 304 https://registry.npmjs.org/bignum
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan

> bignum@0.9.1 install C:\Windows\system32\node_modules\bignum
> node-gyp configure build

C:\Windows\system32\node_modules\bignum>node "C:\nodejs\node_modules\npm\bin\nod
e-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build
gyp: binding.gyp not found (cwd: C:\Windows\system32\node_modules\bignum) while
trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\nodejs\node_modules\npm\node_mod
ules\node-gyp\lib\configure.js:340:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:807:
12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\
bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd C:\Windows\system32\node_modules\bignum
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok
npm ERR! bignum@0.9.1 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bignum@0.9.1 install script.
npm ERR! This is most likely a problem with the bignum package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls bignum
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\nodejs\\\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\n
pm-cli.js" "install" "bignum"
npm ERR! cwd C:\Windows\system32
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Windows\system32\npm-debug.log
npm ERR! not ok code 0

thanks~

**Comment by rvagg** [comment]
you probably need to install Microsoft Visual Studio 2013 Express Desktop Edition, i.e. this needs a compiler in order to install.
