### ISSUE TITLE
Feature request: remainder

### ISSUE THREAD

**Issue by dmarcelino** [justmoon/node-bignum#51]
Hi, thanks for creating node-bignum, I've started using it today and I'm already loving it! :grinning: 

I'd like to suggest creating a `remainder` operation as it can be really useful sometimes. Currently I'm doing the below:

``` javascript
// Big num remainder (not very performant)
function remainder(dividend, divisor, quotient) {
  if(!quotient){
    quotient = dividend.div(divisor);
  }
  return dividend.sub(quotient.mul(divisor));
}
```

which I don't consider ideal by any means. Let me know what you think about the feature or even about a better existing way to get the remainder. Thanks!

**Comment by cscott** [comment]
```
remainder = dividend.mod(divisor);
```
should do what you want.

**Comment by dmarcelino** [comment]
Oh you are right, `mod` stands for modulo which is the remainder. Thanks!
