### ISSUE TITLE
Build fails under iojs 3.0

### ISSUE THREAD

**Issue by iamstarkov** [justmoon/node-bignum#58]
bignum seems to be not buildable on new iojs https://travis-ci.org/iamstarkov/get-tweets/builds/74673553#L99

a lot of errors with node-gyp and nun

**Comment by iamstarkov** [comment]
@justmoon can you help me?

**Comment by justmoon** [comment]
@iamstarkov Travis uses an outdated version of g++, see this issue: https://github.com/nodejs/nan/issues/435

And: https://github.com/travis-ci/travis-ci/issues/1379
