### ISSUE TITLE
Bignum.js doesn't compile with the newest node.js version?

### ISSUE THREAD

**Issue by yoki91** [justmoon/node-bignum#67]
Hi:
The bignum.js can't be complied in the newest version of node.js(v5.00). This is the Error message.
Thanks

gyp ERR! configure error 
gyp ERR! stack Error: "pre" versions of node cannot be installed, use the --nodedir flag instead
gyp ERR! stack     at install (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:64:16)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at getNodeDir (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:155:20)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:194:7)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Linux 4.0.8-040008-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/yifeige/WebstormProjects/Server_B/node_modules/bignum
gyp ERR! node -v v5.0.0-pre
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 4.0.8-040008-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "bignum"
npm ERR! node v5.0.0-pre
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! bignum@0.11.0 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bignum@0.11.0 install script 'node-gyp configure build'.
npm ERR! This is most likely a problem with the bignum package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls bignum
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/yifeige/WebstormProjects/Server_B/node_modules/npm-debug.log

**Comment by Patman64** [comment]
Just compiled it fine under Windows x64.

Looks like this is your problem: http://stackoverflow.com/questions/18777882/node-gyp-error-while-doing-npm-install

Install the latest non-pre release.

**Comment by erm3nda** [comment]
@Patman64 can u upload compiled stuff to any internet share service?

**Comment by guatedude2** [comment]
I'm still seeing this issue
