### ISSUE TITLE
warning on node 6

### ISSUE THREAD

**Issue by zowers** [justmoon/node-bignum#75]
(node) v8::FunctionTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

npm version
{ npm: '3.8.6',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '56.1',
  modules: '48',
  node: '6.0.0',
  openssl: '1.0.2g',
  uv: '1.9.0',
  v8: '5.0.71.35',
  zlib: '1.2.8' }

==== JS stack trace =========================================

Security context: 0x113e158c9fa9 <JS Object>#0#
    1: .node [module.js:568] [pc=0x3d0f2c6b4024] (this=0x302940f19539 <an Object with map 0xda931717609>#1#,module=0x269b1c6b33e9 <a Module with map 0xda9317ed259>#2#,filename=0x269b1c6b33b1 <String[75]: node_modules/bignum/build/Release/bignum.node>)
    2: load [module.js:456] [pc=0x3d0f2c339ad2] (this=0x269b1c6b33e9 <a Module with map 0xda9317ed259>#2#,filename=0x269b1c6b33b1 <String[75]: node_modules/bignum/build/Release/bignum.node>)
    3: tryModuleLoad(aka tryModuleLoad) [module.js:415] [pc=0x3d0f2c3395fd] (this=0x113e15804189 <undefined>,module=0x269b1c6b33e9 <a Module with map 0xda9317ed259>#2#,filename=0x269b1c6b33b1 <String[75]: node_modules/bignum/build/Release/bignum.node>)
    4: _load [module.js:407] [pc=0x3d0f2c335242] (this=0x302940f194a9 <JS Function Module (SharedFunctionInfo 0x957eb4275b1)>#3#,request=0x33434c1fee41 <String[22]: ./build/Release/bignum>,parent=0x269b1c6a8759 <a Module with map 0xda9317ed259>#4#,isMain=0x113e15804299 <false>)
    5: require [module.js:~463] [pc=0x3d0f2c3f04ab] (this=0x269b1c6a8759 <a Module with map 0xda9317ed259>#4#,path=0x33434c1fee41 <String[22]: ./build/Release/bignum>)
    6: new constructor(aka require) [internal/module.js:20] [pc=0x3d0f2c3430e6] (this=0x269b1c6b1e19 <a require with map 0x1063fa0e5f31>#5#,path=0x33434c1fee41 <String[22]: ./build/Release/bignum>)
    8: /* anonymous */ [node_modules/bignum/index.js:4] [pc=0x3d0f2c6b3030] (this=0x269b1c6a87a9 <an Object with map 0x3cb07ab07b71>#6#,exports=0x269b1c6a87a9 <an Object with map 0x3cb07ab07b71>#6#,require=0x269b1c6af839 <JS Function require (SharedFunctionInfo 0x957eb4581d1)>#7#,module=0x269b1c6a8759 <a Module with map 0xda9317ed259>#4#,__filename=0x269b1c6a8721 <String[58]: node_modules/bignum/index.js>,__dirname=0x269b1c6af7d1 <String[49]: node_modules/bignum>)
    9: _compile [module.js:541] [pc=0x3d0f2c3425a4] (this=0x269b1c6a8759 <a Module with map 0xda9317ed259>#4#,content=0x269b1c6a92e1 <Very long string[10636]>#8#,filename=0x269b1c6a8721 <String[58]: node_modules/bignum/index.js>)
   10: .js [module.js:550] [pc=0x3d0f2c33b0cb] (this=0x302940f19539 <an Object with map 0xda931717609>#1#,module=0x269b1c6a8759 <a Module with map 0xda9317ed259>#4#,filename=0x269b1c6a8721 <String[58]: node_modules/bignum/index.js>)
   11: load [module.js:456] [pc=0x3d0f2c339ad2] (this=0x269b1c6a8759 <a Module with map 0xda9317ed259>#4#,filename=0x269b1c6a8721 <String[58]: node_modules/bignum/index.js>)
   12: tryModuleLoad(aka tryModuleLoad) [module.js:415] [pc=0x3d0f2c3395fd] (this=0x113e15804189 <undefined>,module=0x269b1c6a8759 <a Module with map 0xda9317ed259>#4#,filename=0x269b1c6a8721 <String[58]: node_modules/bignum/index.js>)
   13: _load [module.js:407] [pc=0x3d0f2c335242] (this=0x302940f194a9 <JS Function Module (SharedFunctionInfo 0x957eb4275b1)>#3#,request=0x2046e0be9ed1 <String[6]: bignum>,parent=0x269b1c4f3ae1 <a Module with map 0xda9317ed259>#9#,isMain=0x113e15804299 <false>)
   14: require [module.js:~463] [pc=0x3d0f2c3f04ab] (this=0x269b1c4f3ae1 <a Module with map 0xda9317ed259>#9#,path=0x2046e0be9ed1 <String[6]: bignum>)
   15: require(aka require) [internal/module.js:20] [pc=0x3d0f2c3430e6] (this=0x113e15804189 <undefined>,path=0x2046e0be9ed1 <String[6]: bignum>)
==== C stack trace ===============================

 1: v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute)
 2: BigNum::Initialize(v8::Local<v8::Object>)
 3: init
 4: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)
 5: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
 6: 0x98456c
 7: 0x984b0d
 8: 0x3d0f2c20961b

**Comment by Patman64** [comment]
I think this library is dead.

**Comment by rvagg** [comment]
You probably need to reinstall as you may have a slightly outdated version of nan in your dependency tree. New release of bignum coming out shortly that explicitly sets for a newer version but the current version in npm _should_ work just fine all the way up to Node.js' master branch (that's what I'm testing on right now).
