### ISSUE TITLE
A failure at "node-gyp configure build"

### ISSUE THREAD

**Issue by nirav1516** [justmoon/node-bignum#76]
Trying to install "npm install prozess",
Getting mentioned error. Attaching the logs
[npm-debug.txt](https://github.com/justmoon/node-bignum/files/256036/npm-debug.txt)

**Comment by rvagg** [comment]
Not really enough information in there, do you have osx xcode commandline tools installed? Check out the instructions @ http://railsapps.github.io/xcode-command-line-tools.html to get that working.
