### ISSUE TITLE
Cannot find module 'bignum'

### ISSUE THREAD

**Issue by quafoo** [justmoon/node-bignum#80]
when i required the latest version(0.12.2) bignum , there is an error " Cannot find module 'bignum' ".

**Comment by rvagg** [comment]
can you tell me more about what kind of system you are running on, what version of Node and perhaps even the output of `npm install bignum` please? I'm experimenting with node-pre-gyp for downloading binaries and it could be related to that.

**Comment by quafoo** [comment]
system: OS X 10.11.5
node version: 4.4.0
output of `npm install bignum`
`> bignum@0.12.2 preinstall /Users/chanxh/Downloads/node_modules/bignum
> npm install node-pre-gyp

node-pre-gyp@0.6.28 node_modules/node-pre-gyp
├── semver@5.1.0
├── nopt@3.0.6 (abbrev@1.0.9)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── rc@1.1.6 (ini@1.3.4, deep-extend@0.4.1, strip-json-comments@1.0.4, minimist@1.2.0)
├── tar@2.2.1 (block-stream@0.0.9, inherits@2.0.1, fstream@1.0.9)
├── tar-pack@3.1.3 (uid-number@0.0.6, once@1.3.3, debug@2.2.0, readable-stream@2.0.6, fstream@1.0.9, fstream-ignore@1.0.5)
├── rimraf@2.5.2 (glob@7.0.3)
├── npmlog@2.0.4 (ansi@0.3.1, are-we-there-yet@1.1.2, gauge@1.2.7)
└── request@2.72.0 (aws-sign2@0.6.0, tunnel-agent@0.4.3, oauth-sign@0.8.2, forever-agent@0.6.1, caseless@0.11.0, is-typedarray@1.0.0, stringstream@0.0.5, isstream@0.1.2, aws4@1.4.1, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.2.2, node-uuid@1.4.7, qs@6.1.0, combined-stream@1.0.5, bl@1.1.2, hawk@3.1.3, mime-types@2.1.11, form-data@1.0.0-rc4, http-signature@1.1.1, har-validator@2.0.6)
\
> bignum@0.12.2 install /Users/chanxh/Downloads/node_modules/bignum
> node-pre-gyp install --fallback-to-build

[bignum] Success: "/Users/chanxh/Downloads/node_modules/bignum/binding/bignum.node" is installed via remote
bignum@0.12.2 node_modules/bignum
├── bindings@1.2.1
└── nan@2.3.5`

**Comment by rvagg** [comment]
ok, it was a bad publish, try again, 0.12.5 _should_ be better

**Comment by quafoo** [comment]
OK，thank you.
